// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFNtW0cHByVWeQiwWS7keNG5ojLTtXvg',
    appId: '1:660803128429:web:a9740b79b28c4c7b2e4364',
    messagingSenderId: '660803128429',
    projectId: 'quickwash-fb84c',
    authDomain: 'quickwash-fb84c.firebaseapp.com',
    storageBucket: 'quickwash-fb84c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiTnuIBkso_iySFr7U4TK9dT1Ldiy77A',
    appId: '1:660803128429:android:caffbe64b929f1922e4364',
    messagingSenderId: '660803128429',
    projectId: 'quickwash-fb84c',
    storageBucket: 'quickwash-fb84c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqI_6Hhmu-9TXvZ6ZyPMoqB4G7oRWG-_0',
    appId: '1:660803128429:ios:e41451f88d2b31232e4364',
    messagingSenderId: '660803128429',
    projectId: 'quickwash-fb84c',
    storageBucket: 'quickwash-fb84c.appspot.com',
    iosBundleId: 'com.example.carWash',
  );
}
